package lab10;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.startsWith;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class RightMoveTestSuiteTest extends AbstractSeleniumTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new FirefoxDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		

		
		
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void lE2() {
		driver.get("https://www.rightmove.co.uk/");
		driver.findElement(By.id("searchLocation")).click();
		driver.findElement(By.id("searchLocation")).sendKeys("LE2");
		driver.findElement(By.id("buy")).click();
		{
			WebElement dropdown = driver.findElement(By.id("maxPrice"));
			dropdown.findElement(By.xpath("//option[. = '250,000']")).click();
		}
		driver.findElement(By.cssSelector("#maxPrice > option:nth-child(24)")).click();
		{
			WebElement dropdown = driver.findElement(By.id("minPrice"));
			dropdown.findElement(By.xpath("//option[. = '50,000']")).click();
		}
		driver.findElement(By.cssSelector("#minPrice > option:nth-child(2)")).click();
		{
			WebElement dropdown = driver.findElement(By.id("minBedrooms"));
			dropdown.findElement(By.xpath("//option[. = '2']")).click();
		}
		driver.findElement(By.cssSelector("#minBedrooms > option:nth-child(4)")).click();
		{
			WebElement dropdown = driver.findElement(By.id("maxBedrooms"));
			dropdown.findElement(By.xpath("//option[. = 'No max']")).click();
		}
		driver.findElement(By.cssSelector("#maxBedrooms > option:nth-child(1)")).click();
		{
			WebElement dropdown = driver.findElement(By.id("displayPropertyType"));
			dropdown.findElement(By.xpath("//option[. = 'Houses']")).click();
		}
		driver.findElement(By.cssSelector("#displayPropertyType > option:nth-child(2)")).click();
		driver.findElement(By.cssSelector(".tickbox--indicator")).click();
		driver.findElement(By.id("submit")).click();
		assertThat(driver.getTitle(), is("Properties For Sale in LE2 | Rightmove"));
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".searchTitle-saveLabel"));
			assert (elements.size() > 0);
		}
		assertThat(driver.findElement(By.cssSelector(".searchTitle-saveLabel")).getText(), is("Create Alert"));
	}

	@Test
	public void signin() {
		WebDriverWait wait = new WebDriverWait(driver, 60);// 1 minute
		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);		
		driver.get("https://www.rightmove.co.uk/login.html");
		driver.manage().window().setSize(new Dimension(1440, 875));
		driver.findElement(By.id("email")).click();
		driver.findElement(By.id("email")).sendKeys("jmrojas.uk@gmail.com");
		driver.findElement(By.id("password")).click();
		driver.findElement(By.id("password")).sendKeys("co2103demopsw");
		driver.findElement(By.cssSelector(".mrm-button")).click();
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".account-link")));
		assertThat(driver.findElement(By.cssSelector(".account-link")).getText(), is("My Rightmove"));
		driver.findElement(By.cssSelector(".account-link")).click();
		wait.until(ExpectedConditions.frameToBeAvailableAndSwitchToIt("rm-assistant-frame"));
		// driver.switchTo().frame(3);
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("View My Rightmove")));
		driver.findElement(By.linkText("View My Rightmove")).click();
		driver.switchTo().defaultContent();
		assertThat(driver.getTitle(), is("My rightmove"));
		driver.findElement(By.linkText("Log out")).click();
		assertThat(driver.getTitle(),
				is("Rightmove - UK\'s number one property website for properties for sale and to rent"));
	}
}
